name: Build & Test

on: push

jobs:
  skip-or-not:
    name: skip or not
    runs-on: ubuntu-latest

    steps:    
    - name: info
      run: |
        echo User $GITHUB_ACTOR triggered build on $GITHUB_REF by $GITHUB_SHA commit.
      
    - name: skip or not
      id: skipornot
      uses: atlwendy/retrieve-commit-messages-from-pr@v3
    - name: output skip or not
      run: echo ::set-env name=SHOULD_RUN::${{ steps.skipornot.outputs.shouldRun }}
      
    - name: cancelling
      uses: andymckay/cancel-action@0.2
      if: env.SHOULD_RUN == 'false'
    
  build-and-test:
    name: build & test
    runs-on: ubuntu-latest
    needs: [skip-or-not]

    steps:    
    - uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201

    - name: Build sln
      run: dotnet build -c Release --no-cache /clp:NoSummary ./HappyCode.NetCoreBoilerplate.sln

    - name: Test sln
      run: dotnet test -c Release --no-build --filter FullyQualifiedName!~LoadTests /maxcpucount:1 /p:WarningLevel=0 ./HappyCode.NetCoreBoilerplate.sln

  collect-code-coverage:
    name: code coverage
    runs-on: ubuntu-latest
    needs: [build-and-test]

    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201

    - name: Collect code coverage
      run: dotnet test -c Release --filter FullyQualifiedName!~LoadTests /maxcpucount:1 /p:WarningLevel=0 /p:CollectCoverage=true /p:CoverletOutput="../" /p:MergeWith="../coverage.json" /p:CoverletOutputFormat=\"json,opencover\" ./HappyCode.NetCoreBoilerplate.sln

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./test/coverage.opencover.xml
        flags: unittests
